#ifndef MUSIC_PLAYER_CORE_GLOBAL_H
#define MUSIC_PLAYER_CORE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MUSIC_PLAYER_CORE_LIBRARY)
#  define MUSIC_PLAYER_CORE_EXPORT Q_DECL_EXPORT
#else
#  define MUSIC_PLAYER_CORE_EXPORT Q_DECL_IMPORT
#endif

#endif // MUSIC_PLAYER_CORE_GLOBAL_H
